---
title: "ANOVA_METOPROLOL"
author: "Zongyan Wang"
date: "Monday, December 07, 2015"
output: pdf_document
---
## Load package
```{r}
library(data.table)
library(dplyr)
library(agricolae)
library(ggplot2)
```

## data loading and clean
```{r}
phy_drugs = fread("F:/Academic/Stat 992/group project/toy_data/wi_cardi2.tab", sep="\t", header=FALSE)
hospitals = unique(phy_drugs[, 20])
setkey(phy_drugs,V1)
#phy_drugs$zip = DT[as.character(phy_drugs$V1), mult = "first"]$`Zip Code` 
if(T){
  phy_drugs = phy_drugs[`V9`=="METOPROLOL SUCCINATE"]
}


#First aggregate ratios over physicians 
grouped_by_physician = phy_drugs %>% 
  group_by(V1) %>%
  dplyr::select(drug_name = V8, generic_name = V9, total_claim_cnt = V11) 

#Calculates ratios based on number of brand name vs total claims
phy_bg_ratios = dplyr::summarise(grouped_by_physician, 
                          bg_ratio = (sum(as.vector(total_claim_cnt[as.vector(drug_name) != as.vector(generic_name)]))/sum(as.vector(total_claim_cnt)))
)

phy_bg_ratios$hospital <- phy_drugs[.(phy_bg_ratios$V1), mult = "first"]$V20

```




## ANOVA
```{r}
data <-phy_bg_ratios
data <- cbind(data,trt=factor(data$hospital,labels=1:length(unique(data$hospital))))
model <- aov(bg_ratio ~ trt, data = data)
summary(model)
```
The p-value is 7.5 * 10^{-8}, it shows there are significant different among hospital.


## Doing LSD and HSD test
```{r}
lsd.out <- LSD.test(model, "trt", p.adj = "bonferroni")
hsd.out <- HSD.test(model,"trt", group = T)

bar.group(lsd.out$groups,ylim=c(0,45),density=4,border="blue")
bar.group(hsd.out$groups,ylim=c(0,45),density=4,border="blue")

#lsd.out$groups
#hsd.out$groups
```


## You can match the group number with hospital with the data we use
```{r}
id.group <- data %>% 
  dplyr::select(hospital, trt) %>%
  unique() %>%
  arrange(trt)
groups <- as.data.frame(hsd.out$groups)
groups$trt <- as.integer(groups$trt)  
id.group$trt <- as.integer(id.group$trt)
result <- plyr::join(groups, id.group)
result
```
There are three hospitals stand out, which are EDDY D. CO, MD, SC; JOAN T. HARNEY GNADT, MD, SC; MERCY HEALTH SYSTEM CORPORATION.

## plot 
```{r}
result <- result %>% mutate(hospital = 
                              reorder(x = hospital, X = means, min)) 
hospital_HSD <- ggplot(result, aes(x = hospital, y = means)) +
  geom_point(aes(color = M)) +
  geom_text(aes(x = hospital, y = means, 
                label = hospital, color = M), size = 3) +
  ggtitle("BPR over hospital on METOPROLOL") +
  labs(x = "Hospital", y = "means of BPR")
hospital_HSD

ggsave(filename = "hospital_HSD.png", hospital_HSD, width = 8, height = 6, dpi = 300)
```

```{r}
bgmean <- data %>% 
  group_by(trt) %>%
  summarize(BPR = mean(bg_ratio)) %>%
  mutate(hospital = reorder(x = trt, X = BPR, min))
ggplot(bgmean, aes(x = hospital, y = BPR)) +
  geom_point(aes(color = hospital)) +
  ggtitle("BPR over hospitals")
#  geom_text(aes(x = hospital, y = bgMean, label = hospital), size = 2.5)

ggsave(filename = "wi_cardio_METO.png", plot = last_plot())
```
