---
title: "new drug list"
author: "Zongyan Wang"
date: "Monday, November 30, 2015"
output: pdf_document
---
```{r}
if (!require("XML")) {
  install.packages("XML")
  library("XML") # this produces error if loading package fails
}
```
## new drugs for 2013
### find the categories
```{r}
lines = readLines("http://www.centerwatch.com/drug-information/fda-approved-drugs/year/2013")
categories.lines <- grep(pattern = "<h3>.*</h3>", x = lines, value = T)
categories <- gsub(pattern = "<h3>(.*)</h3>", replacement = "\\1", x = categories.lines)
## Remove the whitespace in the strings
categories <- gsub(pattern = " ", replacement = "", x = categories)
## All the categories
categories
categories.lineNum <- grep(pattern = "<h3>.*</h3>", x = lines)
```
### match the medicine name for each categories
```{r}
# Divide the lines into 28 blocks, each block is for one particular category
categoryBlock <- lines[categories.lineNum[1]:categories.lineNum[2]]
# find all the medicine in one particular block
medicine.Line <- grep(pattern = "id=", x = categoryBlock, value = T)
medicine.Line
medicine <- gsub(pattern = "<p><strong><a id(.*)href(.*)>(.+)</a></strong>; (.*);", replacement = "\\3_\\4", x = medicine.Line)
# Remove the whitespace
medicine <- gsub(pattern = "(\\s+)(\\w+.*)", replacement = "\\2", x = medicine)
medicine
```
