---
title: "anova_example"
author: "Zongyan Wang"
date: "Sunday, December 06, 2015"
output: pdf_document
---


```{r}
#Linear modelling on data
# Load package

library(ggplot2)
library(data.table)
library(dplyr)
library(agricolae)
library(igraph)
library('Matrix')
WISC = TRUE
NY = FALSE
setwd("~/projects/data")


if (NY) {
b= c(rep("character", 6),rep("factor",4), "numeric", rep("factor",6), "character", "character", "character", "numeric", rep("character",2), "factor", "character", "factor", "character", rep("character", 10), rep("factor", 6))
wi = fread("ny_DT.txt",colClasses = b)
setkey(wi, NPI)
Ewi = fread("ny_Et.txt",sep = ",",  colClasses = c("character", "character","numeric", "numeric", "numeric"))
setkey(Ewi, V1)
#Import data
phy_drugs = fread("ny_card.txt", sep=",")
}
if (WISC) {
  b= c(rep("character", 6),rep("factor",4), "numeric", rep("factor",6), "character", "character", "character", "numeric", rep("character",2), "factor", "character", "factor", "character", rep("character", 10), rep("factor", 6))
  wi = fread("wi_DT.txt",colClasses = b)
  setkey(wi, NPI)
  Ewi = fread("wi_Et.txt",sep = ",",  colClasses = c("character", "character","numeric", "numeric", "numeric"))
  setkey(Ewi, V1)
  #Import data
  phy_drugs = fread("wi_card_all.txt", sep=",")
}

hospitals = unique(phy_drugs[, 20])
setkey(phy_drugs,NPI)
#phy_drugs = phy_drugs[GENERIC_NAME=="METOPROLOL SUCCINATE"]
phy_drugs = phy_drugs[like(SPECIALTY_DESC,"Cardiology")]

#First aggregate ratios over physicians 
grouped_by_physician = phy_drugs %>% 
  group_by(NPI) %>%
  select(drug_name = DRUG_NAME, generic_name = GENERIC_NAME, total_claim_cnt = TOTAL_CLAIM_COUNT) 

#Calculates ratios based on number of brand name vs total claims
phy_bg_ratios = summarise(grouped_by_physician, 
                          bg_ratio = (sum(as.vector(total_claim_cnt[as.vector(drug_name) != as.vector(generic_name)]))/sum(as.vector(total_claim_cnt)))
)


#Consider graph and its corresponding adjacency matrix
wi_card = wi[unique(as.character(phy_drugs$NPI))]
setkey(Ewi,V1)
Ewi = Ewi[V1 %in% unique(as.character(phy_drugs$NPI))]  # so cool! and fast!
setkey(Ewi,V2)
Ewi = Ewi[V2 %in% unique(as.character(phy_drugs$NPI))]
Ewi = Ewi[complete.cases (Ewi)]  #lots of NA's.  Have not inspected why.
el=as.matrix(Ewi)[,1:2] #igraph needs the edgelist to be in matrix format
g=graph.edgelist(el,directed = F) # this creates a graph.
E(g)$weight=as.numeric(Ewi$V3)

# Calculate models over npis and peers
# Graph matrices (weighted)
numNPI = length(V(g))
A_w = Matrix(get.adjacency(graph = g, attr="weight"), sparse = TRUE) #
#L_w = as.matrix(graph.laplacian(g))
D_w = matrix(data=0,nrow = numNPI,ncol = numNPI)
D_w = Matrix(D_w, sparse = TRUE)
for (i in 1:numNPI){
  D_w[i,i] = 1/sum(A_w[i,])
  if (D_w[i,i]==0) {
    D_w[i,i]=1
  }
} 
#D_w = solve(D_w)
```

#Weighted analysis
```{r}
#Weighted sum of peer ratios matrix
r = as.vector(phy_bg_ratios[.(as.integer(V(g)$name))]$bg_ratio)
peerR_w = D_w%*%A_w%*%r
model_peerR_w = lm(r ~ as.vector(peerR_w))

## An example of how to visualize lm model

## plot with basic package
plot(as.vector(r) ~ as.vector(peerR_w))
abline(model_peerR_w)
ggplot(model_peerR_w, aes(x = as.vector(peerR_w), y = r)) +
  geom_point() +
  stat_smooth(method = "lm") + ggtitle("Physician vs Peer B/G Ratio on Weighed Graph (for MS)") +
  labs(x="Mean Peer B/G Ratio",y="Physician Ratio")

summary(model_peerR_w)
cor.test(as.vector(peerR_w), r)
cor.test(as.vector(peerR_w), r, method = "spearman")

```

#Unweighted case
```{r}
#Calculate matrices (unweighted)
A_u = as.matrix(get.adjacency(graph = g)) #
#L_u = as.matrix(graph.laplacian(g), weight = NA)
D_u = matrix(data=0,nrow = numNPI,ncol = numNPI)
for (i in 1:numNPI){
  D_u[i,i] = 1/sum(A_u[i,])
  if (D_u[i,i]==0) {
    D_u[i,i]=1
  }
} 

#Weighted sum of peer ratios matrix
r = as.vector(phy_bg_ratios[.(as.integer(V(g)$name))]$bg_ratio)
peerR_u = D_u%*%A_u%*%r
model_peerR_u = lm(r ~ peerR_u)
# ## plot withm ggplot
ggplot(model_peerR_u, aes(x = as.vector(peerR_u), y = r)) +
   geom_point() +
   stat_smooth(method = "lm") + ggtitle("Physician vs Peer B/G Ratio on Unweighed Graph (for MS)") +
   labs(x="Mean Peer B/G Ratio",y="Physician Ratio")

summary(model_peerR_u)
cor.test(as.vector(peerR_u), r)
cor.test(as.vector(peerR_u), r, method = "spearman")

## An example of how to visualize lm model

## plot with basic package
plot(as.vector(r) ~ as.vector(peerR_u))
abline(model_peerR_u)

#rr = as.vector(outer(r,r))
rr = matrix(nrow = length(r),ncol = length(r))
for (i in 1:length(r)){
  for (j in 1:length(r)){
    #rr[i,j] = (r[i]-r[j])^2
    rr[i,j] = (r[i]-r[j])^2
  }
}

```